services:
  mysql:
    image: mysql:latest
    container_name: mysql-saveAndServe
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Saveandserve!
      MYSQL_DATABASE: saveandserve
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - saveandserve-network 

  spring-boot-app:
    image: belendelamoneda/saveandserve:0.0.3
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/saveandserve
    depends_on:
      - mysql
    restart: always
    networks:
      - saveandserve-network 

  angular-web:
      image: belendelamoneda/saveandserve_web:0.0.1
      ports:
        - "4200:4200"
      depends_on:
        - spring-boot-app
      restart: always
      networks:
        - saveandserve-network 

networks:
  saveandserve-network:
    driver: bridge

