services:
  mysql:
    image: mysql:latest
    container_name: mysql-saveAndServe
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Saveandserve!
      MYSQL_DATABASE: saveandserve
    volumes:
      - ./mysql-data:/var/lib/mysql
